import { Inter } from "next/font/google";
import "./globals.css";
import { DEFAULT_THEME } from "@/lib/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ammar Mujahid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className={DEFAULT_THEME}>
      <body className={`inter.className bg-[#F0F0F4] dark:bg-primary-darkest `}>
        {children}
      </body>
    </html>
  );
}
